# Desafio 01 – Ingestão e Padronização de Dados do IPCA-15 (IBGE / SIDRA)

Fonte: Tabela 1705 do SIDRA – IPCA15 - Variação mensal, acumulada no ano, 
acumulada em 12 meses e peso mensal, para o índice geral, grupos, subgrupos, 
itens e subitens de produtos e serviços (a partir de fev/2012).

Neste desafio vamos:

1. Consumir a API do SIDRA (tabela 1705) via HTTP (JSON);
2. Coletar a série mensal de jan/2019 a dez/2019 (Brasil, índice geral);
3. Padronizar o DataFrame (tipos, nomes de colunas);
4. Salvar dados brutos e tratados em `data/raw`, `data/processed` e `data/curated`.

In [2]:
# Importação de bibliotecas
from pathlib import Path
import requests
import json
import re
import pyarrow

import pandas as pd

In [3]:
# Definição de diretórios
BASE = Path.cwd().parent # sobe um nível na hierarquia de pastas
raw = BASE / "data" / "raw"
processed = BASE / "data" / "processed"
curated = BASE / "data" / "curated"


for f in [raw, processed, curated]:
    f.mkdir(parents=True, exist_ok=True)
    
BASE, raw, processed, curated

(WindowsPath('c:/workspace/data-engineering-challenge/01-data_ingestion'),
 WindowsPath('c:/workspace/data-engineering-challenge/01-data_ingestion/data/raw'),
 WindowsPath('c:/workspace/data-engineering-challenge/01-data_ingestion/data/processed'),
 WindowsPath('c:/workspace/data-engineering-challenge/01-data_ingestion/data/curated'))

In [4]:
url = "https://servicodados.ibge.gov.br/api/v3/agregados/1936/periodos/-6/variaveis/630|707|708|4032|4033|5956|5957|662|4036|4037?localidades=N1[all]&classificacao=12762[all]"

if "view=flat" not in url:
    separador = "&" if "?" in url else "?"
    url = url + f"{separador}view=flat"
else:
    url = url

url

req = requests.get(url)
data = req.json()
len(data)


raw_path = raw / "ibge_demografica_empresas.json"
with raw_path.open("w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

raw_path

WindowsPath('c:/workspace/data-engineering-challenge/01-data_ingestion/data/raw/ibge_demografica_empresas.json')

In [5]:
# Conversão para DataFrame
df_raw = pd.DataFrame(data)
print(df_raw.shape)
df_raw.head()

header = df_raw.iloc[0]
df = df_raw.iloc[1:].copy()
df.columns = header
df.reset_index(drop=True, inplace=True)

print(df.shape)
df.head()

(6541, 15)
(6540, 15)

,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Brasil (Código),Brasil,Ano (Código),Ano,Variável (Código),Variável,Classificação Nacional de Atividades Econômicas (CNAE 2.0) (Código),Classificação Nacional de Atividades Econômicas (CNAE 2.0),Faixas de pessoal ocupado (Código),Faixas de pessoal ocupado
0,1,Brasil,1020,Unidades,4481596,1,Brasil,2016,2016,630,Número de empresas,117897,Total,104029,Total
1,1,Brasil,1020,Unidades,33268,1,Brasil,2016,2016,630,Número de empresas,116830,"A Agricultura, pecuária, produção florestal, p...",104029,Total
2,1,Brasil,1020,Unidades,24909,1,Brasil,2016,2016,630,Número de empresas,116831,"01 Agricultura, pecuária e serviços relacionados",104029,Total
3,1,Brasil,1020,Unidades,6726,1,Brasil,2016,2016,630,Número de empresas,116866,02 Produção florestal,104029,Total
4,1,Brasil,1020,Unidades,1633,1,Brasil,2016,2016,630,Número de empresas,116873,03 Pesca e aquicultura,104029,Total

In [6]:
#Padronização dos nomes das colunas

def padroniza_string(s: str) -> str:
    s = str(s).strip().lower()
    s = re.sub(r"[áàâãä]", "a", s)
    s = re.sub(r"[éèêë]", "e", s)
    s = re.sub(r"[íìîï]", "i", s)
    s = re.sub(r"[óòôõö]", "o", s)
    s = re.sub(r"[úùûü]", "u", s)
    s = re.sub(r"ç", "c", s)
    s = re.sub(r"[^a-z0-9]+", "_", s)
    s = re.sub(r"_+", "_", s)
    s = s.strip("_")
    return s

df.columns = [padroniza_string(c) for c in df.columns]
df.head()

,nivel_territorial_codigo,nivel_territorial,unidade_de_medida_codigo,unidade_de_medida,valor,brasil_codigo,brasil,ano_codigo,ano,variavel_codigo,variavel,classificacao_nacional_de_atividades_economicas_cnae_2_0_codigo,classificacao_nacional_de_atividades_economicas_cnae_2_0,faixas_de_pessoal_ocupado_codigo,faixas_de_pessoal_ocupado
0,1,Brasil,1020,Unidades,4481596,1,Brasil,2016,2016,630,Número de empresas,117897,Total,104029,Total
1,1,Brasil,1020,Unidades,33268,1,Brasil,2016,2016,630,Número de empresas,116830,"A Agricultura, pecuária, produção florestal, p...",104029,Total
2,1,Brasil,1020,Unidades,24909,1,Brasil,2016,2016,630,Número de empresas,116831,"01 Agricultura, pecuária e serviços relacionados",104029,Total
3,1,Brasil,1020,Unidades,6726,1,Brasil,2016,2016,630,Número de empresas,116866,02 Produção florestal,104029,Total
4,1,Brasil,1020,Unidades,1633,1,Brasil,2016,2016,630,Número de empresas,116873,03 Pesca e aquicultura,104029,Total

In [50]:
# Salvar o arquivo processado
processed_path = processed / "ibge_demografica_empresas.parquet"

df_to_save = df.reset_index(drop=True).copy()

df_to_save.to_parquet(str(processed_path), engine="fastparquet", index=False)
processed_path

WindowsPath('c:/workspace/data-engineering-challenge/01-data_ingestion/data/processed/ibge_demografica_empresas.parquet')

Realizando o processo de refinamento

In [84]:
df.columns.tolist()

['nivel_territorial_codigo',
 'nivel_territorial',
 'unidade_de_medida_codigo',
 'unidade_de_medida',
 'valor',
 'brasil_codigo',
 'brasil',
 'ano_codigo',
 'ano',
 'variavel_codigo',
 'variavel',
 'classificacao_nacional_de_atividades_economicas_cnae_2_0_codigo',
 'classificacao_nacional_de_atividades_economicas_cnae_2_0',
 'faixas_de_pessoal_ocupado_codigo',
 'faixas_de_pessoal_ocupado']

In [85]:
cols_keep = [
    "ano_codigo",
    "variavel_codigo",
    "variavel",
    "classificacao_nacional_de_atividades_economicas_cnae_2_0_codigo",
    "classificacao_nacional_de_atividades_economicas_cnae_2_0",
    "faixas_de_pessoal_ocupado_codigo",
    "faixas_de_pessoal_ocupado",
    "valor"
]

df_curated = df[cols_keep].copy()
df_curated.head()

,ano_codigo,variavel_codigo,variavel,classificacao_nacional_de_atividades_economicas_cnae_2_0_codigo,classificacao_nacional_de_atividades_economicas_cnae_2_0,faixas_de_pessoal_ocupado_codigo,faixas_de_pessoal_ocupado,valor
0,2016,630,Número de empresas,117897,Total,104029,Total,4481596
1,2016,630,Número de empresas,116830,"A Agricultura, pecuária, produção florestal, p...",104029,Total,33268
2,2016,630,Número de empresas,116831,"01 Agricultura, pecuária e serviços relacionados",104029,Total,24909
3,2016,630,Número de empresas,116866,02 Produção florestal,104029,Total,6726
4,2016,630,Número de empresas,116873,03 Pesca e aquicultura,104029,Total,1633

In [86]:
df_curated = df_curated.rename(columns={
    "ano_codigo": "ano",
    "variavel_codigo": "variavel_codigo",
    "variavel": "variavel_nome",

    "classificacao_nacional_de_atividades_economicas_cnae_2_0_codigo": "cnae_codigo",
    "classificacao_nacional_de_atividades_economicas_cnae_2_0": "cnae_nome",

    "faixas_de_pessoal_ocupado_codigo": "faixa_ocupados_codigo",
    "faixas_de_pessoal_ocupado": "faixa_ocupados_nome",
})

In [87]:
df_curated.head()

,ano,variavel_codigo,variavel_nome,cnae_codigo,cnae_nome,faixa_ocupados_codigo,faixa_ocupados_nome,valor
0,2016,630,Número de empresas,117897,Total,104029,Total,4481596
1,2016,630,Número de empresas,116830,"A Agricultura, pecuária, produção florestal, p...",104029,Total,33268
2,2016,630,Número de empresas,116831,"01 Agricultura, pecuária e serviços relacionados",104029,Total,24909
3,2016,630,Número de empresas,116866,02 Produção florestal,104029,Total,6726
4,2016,630,Número de empresas,116873,03 Pesca e aquicultura,104029,Total,1633

In [88]:
#tipagem
df_curated["ano"] = df_curated["ano"].astype(int)
df_curated["variavel_codigo"] = df_curated["variavel_codigo"].astype(int)
df_curated["variavel_nome"] = df_curated["variavel_nome"].astype(str)
df_curated["cnae_codigo"] = df_curated["cnae_codigo"].astype(int)
df_curated["cnae_nome"] = df_curated["cnae_nome"].astype(str)
df_curated["faixa_ocupados_codigo"] = df_curated["faixa_ocupados_codigo"].astype(int)

df_curated["valor"] = pd.to_numeric(df_curated["valor"], errors="coerce")

df_curated.head()

,ano,variavel_codigo,variavel_nome,cnae_codigo,cnae_nome,faixa_ocupados_codigo,faixa_ocupados_nome,valor
0,2016,630,Número de empresas,117897,Total,104029,Total,4481596.0
1,2016,630,Número de empresas,116830,"A Agricultura, pecuária, produção florestal, p...",104029,Total,33268.0
2,2016,630,Número de empresas,116831,"01 Agricultura, pecuária e serviços relacionados",104029,Total,24909.0
3,2016,630,Número de empresas,116866,02 Produção florestal,104029,Total,6726.0
4,2016,630,Número de empresas,116873,03 Pesca e aquicultura,104029,Total,1633.0

In [89]:
# remoção de linhas totais

df_curated = df_curated[
    ~(df_curated["cnae_nome"].str.lower().eq("total"))
]

df_curated.head()

,ano,variavel_codigo,variavel_nome,cnae_codigo,cnae_nome,faixa_ocupados_codigo,faixa_ocupados_nome,valor
1,2016,630,Número de empresas,116830,"A Agricultura, pecuária, produção florestal, p...",104029,Total,33268.0
2,2016,630,Número de empresas,116831,"01 Agricultura, pecuária e serviços relacionados",104029,Total,24909.0
3,2016,630,Número de empresas,116866,02 Produção florestal,104029,Total,6726.0
4,2016,630,Número de empresas,116873,03 Pesca e aquicultura,104029,Total,1633.0
5,2016,630,Número de empresas,116880,B Indústrias extrativas,104029,Total,10295.0

In [90]:
# salvar o arquivo curated

curated_path = curated / "empresas_por_cnae_curated.parquet"
df_curated.to_parquet(curated_path, engine="fastparquet", index=False)
curated_path

WindowsPath('c:/workspace/data-engineering-challenge/01-data_ingestion/data/curated/empresas_por_cnae_curated.parquet')

### Explorando os dados e trazendo insights

In [91]:
print("Anos:", df_curated['ano'].unique())
print("CNAEs distintos:", df_curated['cnae_codigo'].nunique())
print("Faixas ocupados:", df_curated['faixa_ocupados_nome'].unique())
print("Variáveis:", df_curated['variavel_nome'].unique())

Anos: [2016 2017 2018 2019 2020 2021]
CNAEs distintos: 108
Faixas ocupados: ['Total']
Variáveis: ['Número de empresas' 'Pessoal ocupado total'
 'Pessoal ocupado assalariado'
 'Pessoal ocupado assalariado do sexo masculino das empresas'
 'Pessoal ocupado assalariado do sexo feminino das empresas'
 'Pessoal assalariado médio do sexo masculino das empresas'
 'Pessoal assalariado médio do sexo feminino das empresas'
 'Salários e outras remunerações'
 'Salários e outras remunerações dos empregados do sexo masculino das empresas'
 'Salários e outras remunerações dos empregados do sexo feminino das empresas']

In [92]:
print("Serviços de TI:", df_curated[df_curated['cnae_nome'].str.contains('62 Atividades dos serviços de tecnologia da informação', case=False)])

Serviços de TI:        ano  variavel_codigo  \
65    2016              630
174   2016              707
283   2016              708
392   2016             4032
501   2016             4033
610   2016             5956
719   2016             5957
828   2016              662
937   2016             4036
1046  2016             4037
1155  2017              630
1264  2017              707
1373  2017              708
1482  2017             4032
1591  2017             4033
1700  2017             5956
1809  2017             5957
1918  2017              662
2027  2017             4036
2136  2017             4037
2245  2018              630
2354  2018              707
2463  2018              708
2572  2018             4032
2681  2018             4033
2790  2018             5956
2899  2018             5957
3008  2018              662
3117  2018             4036
3226  2018             4037
3335  2019              630
3444  2019              707
3553  2019              708
3662  2019             4032
3771  2019             4033
3880  2019             5956
3989  2019             5957
4098  2019              662
4207  2019             4036
4316  2019             4037
4425  2020              630
4534  2020              707
4643  2020              708
4752  2020             4032
4861  2020             4033
4970  2020             5956
5079  2020             5957
5188  2020              662
5297  2020             4036
5406  2020             4037
5515  2021              630
5624  2021              707
5733  2021              708
5842  2021             4032
5951  2021             4033
6060  2021             5956
6169  2021             5957
6278  2021              662
6387  2021             4036
6496  2021             4037

                                          variavel_nome  cnae_codigo  \
65                                   Número de empresas       117594
174                               Pessoal ocupado total       117594
283                         Pessoal ocupado assalariado       117594
392   Pessoal ocupado assalariado do sexo masculino ...       117594
501   Pessoal ocupado assalariado do sexo feminino d...       117594
610   Pessoal assalariado médio do sexo masculino da...       117594
719   Pessoal assalariado médio do sexo feminino das...       117594
828                      Salários e outras remunerações       117594
937   Salários e outras remunerações dos empregados ...       117594
1046  Salários e outras remunerações dos empregados ...       117594
1155                                 Número de empresas       117594
1264                              Pessoal ocupado total       117594
1373                        Pessoal ocupado assalariado       117594
1482  Pessoal ocupado assalariado do sexo masculino ...       117594
1591  Pessoal ocupado assalariado do sexo feminino d...       117594
1700  Pessoal assalariado médio do sexo masculino da...       117594
1809  Pessoal assalariado médio do sexo feminino das...       117594
1918                     Salários e outras remunerações       117594
2027  Salários e outras remunerações dos empregados ...       117594
2136  Salários e outras remunerações dos empregados ...       117594
2245                                 Número de empresas       117594
2354                              Pessoal ocupado total       117594
2463                        Pessoal ocupado assalariado       117594
2572  Pessoal ocupado assalariado do sexo masculino ...       117594
2681  Pessoal ocupado assalariado do sexo feminino d...       117594
2790  Pessoal assalariado médio do sexo masculino da...       117594
2899  Pessoal assalariado médio do sexo feminino das...       117594
3008                     Salários e outras remunerações       117594
3117  Salários e outras remunerações dos empregados ...       117594
3226  Salários e outras remunerações dos empregados ...       117594
3335                                 Número de empresas       117594
3444                              Pessoal ocupado total       117594
3553                        Pessoal ocupado assalariado       117594
3662  Pessoal ocupado assalariado do sexo masculino ...       117594
3771  Pessoal ocupado assalariado do sexo feminino d...       117594
3880  Pessoal assalariado médio do sexo masculino da...       117594
3989  Pessoal assalariado médio do sexo feminino das...       117594
4098                     Salários e outras remunerações       117594
4207  Salários e outras remunerações dos empregados ...       117594
4316  Salários e outras remunerações dos empregados ...       117594
4425                                 Número de empresas       117594
4534                              Pessoal ocupado total       117594
4643                        Pessoal ocupado assalariado       117594
4752  Pessoal ocupado assalariado do sexo masculino ...       117594
4861  Pessoal ocupado assalariado do sexo feminino d...       117594
4970  Pessoal assalariado médio do sexo masculino da...       117594
5079  Pessoal assalariado médio do sexo feminino das...       117594
5188                     Salários e outras remunerações       117594
5297  Salários e outras remunerações dos empregados ...       117594
5406  Salários e outras remunerações dos empregados ...       117594
5515                                 Número de empresas       117594
5624                              Pessoal ocupado total       117594
5733                        Pessoal ocupado assalariado       117594
5842  Pessoal ocupado assalariado do sexo masculino ...       117594
5951  Pessoal ocupado assalariado do sexo feminino d...       117594
6060  Pessoal assalariado médio do sexo masculino da...       117594
6169  Pessoal assalariado médio do sexo feminino das...       117594
6278                     Salários e outras remunerações       117594
6387  Salários e outras remunerações dos empregados ...       117594
6496  Salários e outras remunerações dos empregados ...       117594

                                              cnae_nome  \
65    62 Atividades dos serviços de tecnologia da in...
174   62 Atividades dos serviços de tecnologia da in...
283   62 Atividades dos serviços de tecnologia da in...
392   62 Atividades dos serviços de tecnologia da in...
501   62 Atividades dos serviços de tecnologia da in...
610   62 Atividades dos serviços de tecnologia da in...
719   62 Atividades dos serviços de tecnologia da in...
828   62 Atividades dos serviços de tecnologia da in...
937   62 Atividades dos serviços de tecnologia da in...
1046  62 Atividades dos serviços de tecnologia da in...
1155  62 Atividades dos serviços de tecnologia da in...
1264  62 Atividades dos serviços de tecnologia da in...
1373  62 Atividades dos serviços de tecnologia da in...
1482  62 Atividades dos serviços de tecnologia da in...
1591  62 Atividades dos serviços de tecnologia da in...
1700  62 Atividades dos serviços de tecnologia da in...
1809  62 Atividades dos serviços de tecnologia da in...
1918  62 Atividades dos serviços de tecnologia da in...
2027  62 Atividades dos serviços de tecnologia da in...
2136  62 Atividades dos serviços de tecnologia da in...
2245  62 Atividades dos serviços de tecnologia da in...
2354  62 Atividades dos serviços de tecnologia da in...
2463  62 Atividades dos serviços de tecnologia da in...
2572  62 Atividades dos serviços de tecnologia da in...
2681  62 Atividades dos serviços de tecnologia da in...
2790  62 Atividades dos serviços de tecnologia da in...
2899  62 Atividades dos serviços de tecnologia da in...
3008  62 Atividades dos serviços de tecnologia da in...
3117  62 Atividades dos serviços de tecnologia da in...
3226  62 Atividades dos serviços de tecnologia da in...
3335  62 Atividades dos serviços de tecnologia da in...
3444  62 Atividades dos serviços de tecnologia da in...
3553  62 Atividades dos serviços de tecnologia da in...
3662  62 Atividades dos serviços de tecnologia da in...
3771  62 Atividades dos serviços de tecnologia da in...
3880  62 Atividades dos serviços de tecnologia da in...
3989  62 Atividades dos serviços de tecnologia da in...
4098  62 Atividades dos serviços de tecnologia da in...
4207  62 Atividades dos serviços de tecnologia da in...
4316  62 Atividades dos serviços de tecnologia da in...
4425  62 Atividades dos serviços de tecnologia da in...
4534  62 Atividades dos serviços de tecnologia da in...
4643  62 Atividades dos serviços de tecnologia da in...
4752  62 Atividades dos serviços de tecnologia da in...
4861  62 Atividades dos serviços de tecnologia da in...
4970  62 Atividades dos serviços de tecnologia da in...
5079  62 Atividades dos serviços de tecnologia da in...
5188  62 Atividades dos serviços de tecnologia da in...
5297  62 Atividades dos serviços de tecnologia da in...
5406  62 Atividades dos serviços de tecnologia da in...
5515  62 Atividades dos serviços de tecnologia da in...
5624  62 Atividades dos serviços de tecnologia da in...
5733  62 Atividades dos serviços de tecnologia da in...
5842  62 Atividades dos serviços de tecnologia da in...
5951  62 Atividades dos serviços de tecnologia da in...
6060  62 Atividades dos serviços de tecnologia da in...
6169  62 Atividades dos serviços de tecnologia da in...
6278  62 Atividades dos serviços de tecnologia da in...
6387  62 Atividades dos serviços de tecnologia da in...
6496  62 Atividades dos serviços de tecnologia da in...

      faixa_ocupados_codigo faixa_ocupados_nome        valor
65                   104029               Total     64213.00
174                  104029               Total    470748.00
283                  104029               Total    368721.00
392                  104029               Total    244191.00
501                  104029               Total    124530.00
610                  104029               Total    244214.03
719                  104029               Total    125383.71
828                  104029               Total  24190770.00
937                  104029               Total  17772319.00
1046                 104029               Total   6418451.00
1155                 104029               Total     64535.00
1264                 104029               Total    473385.00
1373                 104029               Total    371427.00
1482                 104029               Total    246316.00
1591                 104029               Total    125111.00
1700                 104029               Total    242034.51
1809                 104029               Total    122771.20
1918                 104029               Total  25789378.00
2027                 104029               Total  18944554.00
2136                 104029               Total   6844823.00
2245                 104029               Total     66612.00
2354                 104029               Total    496504.00
2463                 104029               Total    391974.00
2572                 104029               Total    259947.00
2681                 104029               Total    132027.00
2790                 104029               Total    251334.62
2899                 104029               Total    127490.74
3008                 104029               Total  27196941.00
3117                 104029               Total  19971359.00
3226                 104029               Total   7225582.00
3335                 104029               Total     78773.00
3444                 104029               Total    542353.00
3553                 104029               Total    425478.00
3662                 104029               Total    280361.00
3771                 104029               Total    145117.00
3880                 104029               Total    273961.28
3989                 104029               Total    140720.91
4098                 104029               Total  30249038.00
4207                 104029               Total  22139115.00
4316                 104029               Total   8109923.00
4425                 104029               Total     87291.00
4534                 104029               Total    570861.00
4643                 104029               Total    442432.00
4752                 104029               Total    291397.00
4861                 104029               Total    151035.00
4970                 104029               Total    280290.89
5079                 104029               Total    144800.57
5188                 104029               Total  33111981.00
5297                 104029               Total  24192354.00
5406                 104029               Total   8919627.00
5515                 104029               Total    104037.00
5624                 104029               Total    673621.00
5733                 104029               Total    526758.00
5842                 104029               Total    342902.00
5951                 104029               Total    183856.00
6060                 104029               Total    315693.18
6169                 104029               Total    165973.36
6278                 104029               Total  41811316.00
6387                 104029               Total  30388440.00
6496                 104029               Total  11422876.00

In [93]:
# Analise por genero e salario e tipo de cnae:

# variáveis de salário por gênero
var_nome = df_curated["variavel_nome"].isin([
    "Salários e outras remunerações dos empregados do sexo masculino das empresas",
    "Salários e outras remunerações dos empregados do sexo feminino das empresas",
])

# CNAE 62 - serviços de TI
cnae_ti = df_curated["cnae_nome"].str.contains(
    "62 Atividades dos serviços de tecnologia da informação",
    case=False,
    na=False
)

# aplica os dois filtros ao mesmo tempo
df_genero_salario = (
    df_curated[var_nome & cnae_ti]
    .groupby(["ano", "cnae_nome", "variavel_nome"])["valor"]
    .sum()
    .unstack()
)

# renomeia colunas
df_genero_salario = df_genero_salario.rename(columns={
    "Salários e outras remunerações dos empregados do sexo masculino das empresas": "salario_masc",
    "Salários e outras remunerações dos empregados do sexo feminino das empresas": "salario_fem",
})

df_genero_salario.head()

,variavel_nome,salario_fem,salario_masc
ano,cnae_nome,,
2016,62 Atividades dos serviços de tecnologia da informação,6418451.0,17772319.0
2017,62 Atividades dos serviços de tecnologia da informação,6844823.0,18944554.0
2018,62 Atividades dos serviços de tecnologia da informação,7225582.0,19971359.0
2019,62 Atividades dos serviços de tecnologia da informação,8109923.0,22139115.0
2020,62 Atividades dos serviços de tecnologia da informação,8919627.0,24192354.0

In [95]:
# Dados agregados por genero (empregados) e cnae

#variavel de genero (empregados)
var_genero = df_curated.variavel_nome.isin([
        "Pessoal ocupado assalariado do sexo masculino das empresas",
        "Pessoal ocupado assalariado do sexo feminino das empresas"
    ])

# CNAE 62 - serviços de TI
cnae_ti = df_curated["cnae_nome"].str.contains(
    "62 Atividades dos serviços de tecnologia da informação",
    case=False,
    na=False
)

df_genero = (
    df_curated[var_genero & cnae_ti]
    .groupby(["ano", "cnae_nome", "variavel_nome"])["valor"]
    .sum()
    .unstack()
)

df_genero = df_genero.rename(columns={
    "Pessoal ocupado assalariado do sexo masculino das empresas": "empregados_masc",
    "Pessoal ocupado assalariado do sexo feminino das empresas": "empregadas_fem",
})

df_genero.head()

,variavel_nome,empregadas_fem,empregados_masc
ano,cnae_nome,,
2016,62 Atividades dos serviços de tecnologia da informação,124530.0,244191.0
2017,62 Atividades dos serviços de tecnologia da informação,125111.0,246316.0
2018,62 Atividades dos serviços de tecnologia da informação,132027.0,259947.0
2019,62 Atividades dos serviços de tecnologia da informação,145117.0,280361.0
2020,62 Atividades dos serviços de tecnologia da informação,151035.0,291397.0

In [96]:
# Confirmação de ordenação dos índices
df_genero_salario = df_genero_salario.sort_index()
df_genero = df_genero.sort_index()

In [97]:
# Cálculo do salário médio por gênero
df_avg_salario = pd.DataFrame(index=df_genero.index)

df_avg_salario["sal_medio_masc"] = (
    df_genero_salario["salario_masc"] / df_genero["empregados_masc"]
)

df_avg_salario["sal_medio_fem"] = (
    df_genero_salario["salario_fem"] / df_genero["empregadas_fem"]
)


df_avg_salario.head(50)

,,sal_medio_masc,sal_medio_fem
ano,cnae_nome,,
2016,62 Atividades dos serviços de tecnologia da informação,72.780401,51.541404
2017,62 Atividades dos serviços de tecnologia da informação,76.911585,54.710002
2018,62 Atividades dos serviços de tecnologia da informação,76.828580,54.728063
2019,62 Atividades dos serviços de tecnologia da informação,78.966458,55.885410
2020,62 Atividades dos serviços de tecnologia da informação,83.021973,59.056689
2021,62 Atividades dos serviços de tecnologia da informação,88.621355,62.129471